### ISSUE TITLE
Can’t select a file from the main folder

### ISSUE THREAD

**Issue by au-mikey** [chof747/octoprint-autoprint#8]
For me to be able to select a file to schedule, the file needs to be in a folder and that folder needs to be selected in settings. This should be changed so that you can select any file from any location

**Comment by chof747** [comment]
I am considering this right now for the next version, to change the way files can be selected. Will be included soon

**Comment by chof747** [comment]
Dear @au-mikey, I have changed the functionality so that any file from any folder can be printed now. If you would like to beta-test the feature if this meets your request above, please manually install the following zip (and replace it afterwards against the main version from the repository):

https://github.com/chof747/octoprint-autoprint/archive/refs/heads/8-select-all-files.zip

and comment here so that I can merge it to the master branch and release a new version. 
Thx chof747

**Comment by au-mikey** [comment]
It works, but can be a bit cumbersome to browse when there are multiple files. Is it possible to select the file from OctoPrint file browser or duplicate the file browser with a search function in the tab?

**Comment by chof747** [comment]
Good idea, but to close this one, I created a new issue (#9) to follow up on this.
